services:
  public:
    build:
      context: .
      dockerfile: ./django-site/Dockerfile.public
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    volumes:
      - .:/code
    expose:
      - 8000
    #ports:
    #  - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

  api:
    build:
      context: .
      dockerfile: ./django-site/Dockerfile.api
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    volumes:
      - .:/code
    expose: #Pour savoir pour toi quel port tu utilises.
      - 8001
    #ports:
    #  - "8001:8001"
    #neuille
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Nginx sera exposé sur le port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - public
      - api
    networks:
      - mynetwork


volumes:
  postgres_data:
networks:
  mynetwork: