# Generated by Django 5.1 on 2024-09-03 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public", "0002_remove_armes_skins_remove_inventaires_weapons_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="armes",
            name="skin",
        ),
        migrations.RemoveField(
            model_name="inventaires",
            name="weapon",
        ),
        migrations.AddField(
            model_name="armes",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weapons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventaires",
            name="weapons",
            field=models.ManyToManyField(
                blank=True, related_name="inventories", to="public.armes"
            ),
        ),
        migrations.AddField(
            model_name="skins",
            name="weapon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skins",
                to="public.armes",
            ),
        ),
    ]
