# Generated by Django 5.1 on 2024-09-03 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="armes",
            name="skins",
        ),
        migrations.RemoveField(
            model_name="inventaires",
            name="weapons",
        ),
        migrations.AddField(
            model_name="armes",
            name="skin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weapons",
                to="public.skins",
            ),
        ),
        migrations.AddField(
            model_name="inventaires",
            name="weapon",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="public.armes",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventaires",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
