# Generated by Django 5.1 on 2024-09-03 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public", "0003_remove_armes_skin_remove_inventaires_weapon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="armes",
            name="user",
        ),
        migrations.RemoveField(
            model_name="inventaires",
            name="weapons",
        ),
        migrations.AddField(
            model_name="armes",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weapons",
                to="public.inventaires",
            ),
        ),
        migrations.AlterField(
            model_name="inventaires",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
