# Generated by Django 4.2.16 on 2024-09-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_bungalow_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='bungalow',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bungalow',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
