# Generated by Django 5.1 on 2024-09-03 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="armes",
            name="skins",
        ),
        migrations.RemoveField(
            model_name="inventaires",
            name="weapons",
        ),
        migrations.RemoveField(
            model_name="inventaires",
            name="user",
        ),
        migrations.DeleteModel(
            name="Skins",
        ),
        migrations.DeleteModel(
            name="Armes",
        ),
        migrations.DeleteModel(
            name="Inventaires",
        ),
    ]
