# Generated by Django 5.1 on 2024-09-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Armes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weapon_type", models.CharField(max_length=50)),
                ("damage", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Skins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rarity", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Inventaires",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_api",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("weapons", models.ManyToManyField(blank=True, to="api.armes")),
            ],
        ),
        migrations.AddField(
            model_name="armes",
            name="skins",
            field=models.ManyToManyField(blank=True, to="api.skins"),
        ),
    ]
