# Generated by Django 5.1 on 2024-09-03 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skins",
            name="weapon",
        ),
        migrations.RemoveField(
            model_name="inventaires",
            name="user",
        ),
        migrations.DeleteModel(
            name="Armes",
        ),
        migrations.DeleteModel(
            name="Skins",
        ),
        migrations.DeleteModel(
            name="Inventaires",
        ),
    ]
